###
GET http://localhost:8080/usuarios
///
###
GET http://localhost:8080/usuarios/1

###
## 
### Crear usuario
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nombre": "lucia",
  "email": "wilucillys@gmail.com",
  "password": "01234"
}

###

### actualizar
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nombre": "Ana Actualizada",
  "email": "nuevo@mail.com"
}
###
// Este ejemplo tiene datos de entrada inválidos para probar la validación
{
  "nombre": "",
  "email": "correo-malo",
  "password": "123"
}

###gt eliminar
DELETE http://localhost:8080/usuarios/3