
///
###
GET http://localhost:8080/usuarios/6

## 
### Crear usuario


###

### actualizar
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nombre": "Ana Actualizada",
  "email": "nuevo@mail.com"
}
###
// Este ejemplo tiene datos de entrada inválidos para probar la validación
{
  "nombre": "",
  "email": "correo-malo",
  "password": "123"
}

###gt eliminar
DELETE http://localhost:8080/usuarios/3

### GET usuarios con token
GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvQGVtYWlsLmNvbSIsImlhdCI6MTc3MzA4ODM4OCwiZXhwIjoxNzczMTc0Nzg4fQ.Galt9P5fdJ-FgblxstKiZIqL-nKmzdblEeBbbWCPzAE

###
###
### LOGIN con datos correctos que no crean un nuevo usuario
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "usuario@email.com",
  "password": "123"
}

### USAR TOKEN
GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvQGVtYWlsLmNvbSIsImlhdCI6MTc3MzA4MzcyOSwiZXhwIjoxNzczMTcwMTI5fQ.UAHODZDEIlKrkqNgdzfMgIe6f1yQneOlnln3CCxImeE

###

POST http://localhost:8080/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvQGVtYWlsLmNvbSIsImlhdCI6MTc3MzA4MzcyOSwiZXhwIjoxNzczMTcwMTI5fQ.UAHODZDEIlKrkqNgdzfMgIe6f1yQneOlnln3CCxImeE

{
  "nombre": "karla",
  "email": "karla@gmail.com",
  "password": "0987654321"
}


###
POST http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvQGVtYWlsLmNvbSIsImlhdCI6MTc3MzA4MzcyOSwiZXhwIjoxNzczMTcwMTI5fQ.UAHODZDEIlKrkqNgdzfMgIe6f1yQneOlnln3CCxImeE
Content-Type: application/json

{
  "nombre": "Carlos",
  "email": "carlos@gmail.com",
  "password": "123456"
}